/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef taxi_CONSTANTS_H
#define taxi_CONSTANTS_H

#include "taxi_types.h"

namespace taxi {

class taxiConstants {
 public:
  taxiConstants();

  std::vector<STR>  CommonProperties;
};

extern const taxiConstants g_taxi_constants;

} // namespace

#endif
