/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "taxi_constants.h"

namespace taxi {

const taxiConstants g_taxi_constants;

taxiConstants::taxiConstants() {
}

} // namespace

